server:
  domain: user
  version: 1.0
  jwtSecret: FanOne
  grpcAddress: "127.0.0.1:10010"

mysql:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: my_grpc
  username: root
  password: CYHa0616
  charset: utf8mb4

etcd:
  address: 127.0.0.1:2379

redis:
  address: 127.0.0.1:6379
  password: 